---
services:
  overseerr:
    image: docker.io/sctx/overseerr:latest
    container_name: overseerr
    hostname: overseerr
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      - TZ=Europe/Stockholm
      - PUID=1000
      - PGID=1000
    ports:
      - 5055:5055/tcp
    volumes:
      - $HOME/containers/storage/overseerr/config:/app/config:rw
      - /etc/localtime:/etc/localtime:ro
    networks:
      - proxy

networks:
  proxy:
    external: true