---
services:
  postgres:
    image: docker.io/library/postgres:17
    container_name: postgres
    hostname: postgres
    restart: unless-stopped
    network_mode: host
    security_opt:
      - no-new-privileges:true
    environment:
      - TZ=${TZ}
      - PGDATA=${PGDATA}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 10s
      retries: 5
    volumes:
      - postgres-data:/var/lib/postgresql/data:rw
      - /etc/localtime:/etc/localtime:ro

  zabbix-backend:
    image: docker.io/zabbix/zabbix-server-pgsql:latest
    container_name: zabbix-backend
    hostname: zabbix-backend
    restart: unless-stopped
    network_mode: host
    security_opt:
      - no-new-privileges:true
    environment:
      - TZ=${TZ}
      - DB_SERVER_HOST=${DB_SERVER_HOST}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - /opt/stacks/zabbix/alertscripts:/usr/lib/zabbix/alertscripts:rw
      - /opt/stacks/zabbix/externalscripts:/usr/lib/zabbix/externalscripts:rw
      - /opt/stacks/zabbix/export:/var/lib/zabbix/export:rw
      - /opt/stacks/zabbix/snmptraps:/var/lib/zabbix/snmptraps:rw
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      postgres:
        condition: service_healthy

  zabbix-frontend:
    image: docker.io/zabbix/zabbix-web-nginx-pgsql:latest
    container_name: zabbix-frontend
    hostname: zabbix-frontend
    restart: unless-stopped
    network_mode: host
    security_opt:
      - no-new-privileges:true
    environment:
      - TZ=${TZ}
      - DB_SERVER_HOST=${DB_SERVER_HOST}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - ZBX_SERVER_HOST=${ZBX_SERVER_HOST}
      - PHP_TZ=${TZ}
    volumes:
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      postgres:
        condition: service_healthy
      zabbix-backend:
        condition: service_started

volumes:
  postgres-data:
    external: true