---
services:
  plex:
    image: docker.io/plexinc/pms-docker:latest
    container_name: plex
    hostname: plex.thenoisykeyboard.com
    restart: unless-stopped
    network_mode: host
    security_opt:
      - no-new-privileges:true
    environment:
      - TZ=Europe/Stockholm
      - PLEX_UID=1000
      - PLEX_GID=1000
      - VERSION=docker
      - PLEX_CLAIM=*****
    ports:
      - 32400:32400/tcp
      - 1900:1900/udp
      - 3005:3005/tcp
      - 8324:8324/udp
      - 32469:32469/tcp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    volumes:
      - $HOME/containers/storage/plex:/config:rw
      - $HOME/containers/storage/plex:/transcode:rw
      - /mnt/hdd:/data:ro
      - /mnt/nvme/media:/download:rw
      - /etc/localtime:/etc/localtime:ro