services:
  filebrowser:
    image: docker.io/filebrowser/filebrowser:latest
    container_name: filebrowser
    hostname: filebrowser
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - FB_USERNAME=${FB_USERNAME}
      - FB_PASSWORD=${FB_PASSWORD}
      - FB_PORT=${FB_PORT}
    healthcheck:
      disable: true
    ports:
      - 8005:8005/tcp
    volumes:
      - /opt/stacks/filebrowser/config:/config:rw
      - /opt/stacks/filebrowser/database:/database:rw
      - /:/srv:rw
      - /etc/localtime:/etc/localtime:ro
    networks:
      - proxy
networks:
  proxy:
    external: true