---
services:
  Pulse:
    image: ghcr.io/rcourtman/pulse:latest
    container_name: pulse
    hostname: pulse
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    env_file:
      - .env
    ports:
      - 7655:7655/tcp
    volumes:
      - $HOME/containers/storage/pulse/data:/data:rw
      - /etc/localtime:/etc/localtime:ro
    networks:
      - proxy

networks:
  proxy:
    external: true