---
services:
  dozzle:
    image: ghcr.io/amir20/dozzle:latest
    container_name: dozzle
    hostname: dozzle
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      - TZ=Europe/Stockholm
      - DOZZLE_ADDR=:8008
      - DOZZLE_AUTH_PROVIDER=forward-proxy
      - DOZZLE_ENABLE_ACTIONS=true
      - DOZZLE_HOSTNAME=zimacube
      - DOZZLE_NO_ANALYTICS=true
      - DOZZLE_REMOTE_AGENT=agent-host:7007
      - DOZZLE_SECRET=thenoisykeyboard
    ports:
      - 8008:8008/tcp
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
    networks:
      - proxy

networks:
  proxy:
    external: true