---
services:
  unpoller:
    image: ghcr.io/unpoller/unpoller:latest
    container_name: unpoller
    hostname: unpoller
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      - TZ=${TZ}
      - UP_INFLUXDB_DISABLE=${UP_INFLUXDB_DISABLE}
      - UP_POLLER_DEBUG=${UP_POLLER_DEBUG}
      - UP_UNIFI_DYNAMIC=${UP_UNIFI_DYNAMIC}
      - UP_PROMETHEUS_HTTP_LISTEN=${UP_PROMETHEUS_HTTP_LISTEN}
      - UP_PROMETHEUS_NAMESPACE=${UP_PROMETHEUS_NAMESPACE}
      - UP_UNIFI_CONTROLLER_0_VERIFY_SSL=${UP_UNIFI_CONTROLLER_0_VERIFY_SSL}
      - UP_UNIFI_CONTROLLER_0_SAVE_ALARMS=${UP_UNIFI_CONTROLLER_0_SAVE_ALARMS}
      - UP_UNIFI_CONTROLLER_0_SAVE_ANOMALIES=${UP_UNIFI_CONTROLLER_0_SAVE_ANOMALIES}
      - UP_UNIFI_CONTROLLER_0_SAVE_EVENTS=${UP_UNIFI_CONTROLLER_0_SAVE_EVENTS}
      - UP_UNIFI_CONTROLLER_0_SAVE_IDS=${UP_UNIFI_CONTROLLER_0_SAVE_IDS}
      - UP_UNIFI_CONTROLLER_0_SAVE_SITES=${UP_UNIFI_CONTROLLER_0_SAVE_SITES}
      - UP_UNIFI_CONTROLLER_0_SAVE_DPI=${UP_UNIFI_CONTROLLER_0_SAVE_DPI}
      - UP_UNIFI_CONTROLLER_0_URL=${UP_UNIFI_CONTROLLER_0_URL}
      - UP_UNIFI_CONTROLLER_0_USER=${UP_UNIFI_CONTROLLER_0_USER}
      - UP_UNIFI_CONTROLLER_0_PASS=${UP_UNIFI_CONTROLLER_0_PASS}
      - UP_UNIFI_CONTROLLER_0_SITE=${UP_UNIFI_CONTROLLER_0_SITE}
    ports:
      - 9130:9130/tcp
    volumes:
      - /etc/localtime:/etc/localtime:ro
    networks:
      - proxy

networks:
  proxy:
    external: true