---
services:
  mariadb:
    image: docker.io/library/mariadb:latest
    container_name: mariadb
    hostname: mariadb
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    env_file:
      - .env
    healthcheck:
      test: "healthcheck.sh --connect"
      start_period: 30s
      interval: 10s
      timeout: 10s
      retries: 5
    ports:
      - 3306:3306/tcp
    volumes:
      - $HOME/containers/storage/mariadb/config:/etc/mysql/conf.d
      - $HOME/containers/storage/mariadb/data:/var/lib/mysql:rw
      - /etc/localtime:/etc/localtime:ro
    networks:
      - proxy

  photoprism:
    image: docker.io/photoprism/photoprism:latest
    container_name: photoprism
    hostname: photoprism
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    env_file:
      - .env
    ports:
      - 2342:2342/tcp
    volumes:
      - $HOME/containers/storage/photoprism:/photoprism/storage:rw
      - /mnt/hdd/photos:/photoprism/originals:ro
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      mariadb:
        condition: service_healthy
    networks:
      - proxy

networks:
  proxy:
    external: true