---
services:
  mariadb:
    image: docker.io/library/mariadb:latest
    container_name: mariadb
    hostname: mariadb
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      - TZ=${TZ}
      - MARIADB_AUTO_UPGRADE=${MARIADB_AUTO_UPGRADE}
      - MARIADB_DATABASE=${MARIADB_DATABASE}
      - MARIADB_INITDB_SKIP_TZINFO=${MARIADB_INITDB_SKIP_TZINFO}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_USER=${MARIADB_USER}
    healthcheck:
      test: "healthcheck.sh --connect"
      start_period: 30s
      interval: 10s
      timeout: 10s
      retries: 5
    ports:
      - 3306:3306/tcp
    volumes:
      - /opt/stacks/mariadb/config:/etc/mysql/conf.d
      - /opt/stacks/mariadb/data:/var/lib/mysql:rw
      - /etc/localtime:/etc/localtime:ro
    networks:
      - proxy

  photoprism:
    image: docker.io/photoprism/photoprism:latest
    container_name: photoprism
    hostname: photoprism
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - PHOTOPRISM_ADMIN_PASSWORD=${PHOTOPRISM_ADMIN_PASSWORD}
      - PHOTOPRISM_ADMIN_USER=${PHOTOPRISM_ADMIN_USER}
      - PHOTOPRISM_DATABASE_DRIVER=${PHOTOPRISM_DATABASE_DRIVER}
      - PHOTOPRISM_DATABASE_NAME=${PHOTOPRISM_DATABASE_NAME}
      - PHOTOPRISM_DATABASE_PASSWORD=${PHOTOPRISM_DATABASE_PASSWORD}
      - PHOTOPRISM_DATABASE_SERVER=${PHOTOPRISM_DATABASE_SERVER}
      - PHOTOPRISM_DATABASE_USER=${PHOTOPRISM_DATABASE_USER}
      - PHOTOPRISM_HTTP_PORT=${PHOTOPRISM_HTTP_PORT}
      - PHOTOPRISM_JPEG_SIZE=${PHOTOPRISM_JPEG_SIZE}
      - PHOTOPRISM_PASSWORD=${PHOTOPRISM_PASSWORD}
      - PHOTOPRISM_PNG_SIZE=${PHOTOPRISM_PNG_SIZE}
      - PHOTOPRISM_SITE_TITLE=${PHOTOPRISM_SITE_TITLE}
      - PHOTOPRISM_SITE_URL=${PHOTOPRISM_SITE_URL}
      - PHOTOPRISM_THUMB_FILTER=${PHOTOPRISM_THUMB_FILTER}
      - PHOTOPRISM_THUMB_SIZE=${PHOTOPRISM_THUMB_SIZE}
      - PHOTOPRISM_THUMB_SIZE_UNCACHED=${PHOTOPRISM_THUMB_SIZE_UNCACHED}
      - PHOTOPRISM_THUMB_UNCACHED=${PHOTOPRISM_THUMB_UNCACHED}
      - PHOTOPRISM_USERNAME=${PHOTOPRISM_USERNAME}
    ports:
      - 2342:2342/tcp
    volumes:
      - /opt/stacks/photoprism:/photoprism/storage:rw
      - /mnt/hdd/photos:/photoprism/originals:ro
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      mariadb:
        condition: service_healthy
    networks:
      - proxy

networks:
  proxy:
    external: true