---
services:
  redis:
    image: docker.io/library/redis:latest
    container_name: redis
    hostname: redis
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      - TZ=${TZ}
    ports:
      - 6379:6379/tcp
    volumes:
      - /opt/stacks/redis/data:/data:rw
      - /etc/localtime:/etc/localtime:ro
    networks:
      - proxy

  paperless-ngx:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    container_name: paperless-ngx
    hostname: paperless-ngx
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      - TZ=${TZ}
      - PAPERLESS_ADMIN_USER=${PAPERLESS_ADMIN_USER}
      - PAPERLESS_ADMIN_PASSWORD=${PAPERLESS_ADMIN_PASSWORD}
      - PAPERLESS_ADMIN_EMAIL=${PAPERLESS_ADMIN_EMAIL}
      - PAPERLESS_OCR_LANGUAGE=${PAPERLESS_OCR_LANGUAGE}
      - PAPERLESS_PORT=${PAPERLESS_PORT}
      - PAPERLESS_REDIS=${PAPERLESS_REDIS}
      - PAPERLESS_SECRET_KEY=${PAPERLESS_SECRET_KEY}
      - PAPERLESS_TIME_ZONE=${PAPERLESS_TIME_ZONE}
      - PAPERLESS_URL=${PAPERLESS_URL}
    ports:
      - 8000:8000/tcp
    volumes:
      - /opt/stacks/paperless/consume:/usr/src/paperless/consume:rw
      - /opt/stacks/paperless/data:/usr/src/paperless/data:rw
      - /opt/stacks/paperless/export:/usr/src/paperless/export:rw
      - /opt/stacks/paperless/media:/usr/src/paperless/media:rw
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - redis
    networks:
      - proxy

networks:
  proxy:
    external: true