---
services:
  telegraf:
    image: docker.io/library/telegraf:latest
    container_name: telegraf
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      - TZ=${TZ}
      - HOST_ETC=${HOST_ETC}
      - HOST_PROC=${HOST_PROC}
      - HOST_SYS=${HOST_SYS}
      - HOST_VAR=${HOST_VAR}
      - HOST_RUN=${HOST_RUN}
      - HOST_MOUNT_PREFIX=${HOST_MOUNT_PREFIX}
      - INFLUX_TOKEN=${INFLUX_TOKEN}
    command: ["--non-strict-env-handling"]
    user: ${UID:-1000}:${GID:-1000}
    group_add:
      - ${DOCKER_GID}
    ports:
      - 8125:8125/tcp
    volumes:
      - /opt/stacks/telegraf/config/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /:/hostfs:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
    networks:
      - proxy

  influxdb:
    image: docker.io/library/influxdb:latest
    container_name: influxdb
    hostname: influxdb
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      - TZ=${TZ}
      - INFLUXD_SESSION_LENGTH=${INFLUXD_SESSION_LENGTH}
      - DOCKER_INFLUXDB_INIT_MODE=${DOCKER_INFLUXDB_INIT_MODE}
      - DOCKER_INFLUXDB_INIT_USERNAME=${DOCKER_INFLUXDB_INIT_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${DOCKER_INFLUXDB_INIT_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${DOCKER_INFLUXDB_INIT_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${DOCKER_INFLUXDB_INIT_BUCKET}
      - DOCKER_INFLUXDB_INIT_RETENTION=${DOCKER_INFLUXDB_INIT_RETENTION}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${DOCKER_INFLUXDB_INIT_ADMIN_TOKEN}
    user: ${UID:-1000}:${GID:-1000}
    ports:
      - 8086:8086/tcp
    volumes:
      - /opt/stacks/influxdb/config/config.yaml:/etc/influxdb2/config.yaml:ro
      - /opt/stacks/influxdb/config:/etc/influxdb2:rw
      - influxdb-data:/var/lib/influxdb2:rw
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - telegraf
    networks:
      - proxy

volumes:
  influxdb-data:
    name: influxdb-data
    external: true

networks:
  proxy:
    external: true