---
services:
  dockge:
    image: docker.io/louislam/dockge:latest
    container_name: dockge
    hostname: dockge
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      - TZ=Europe/Stockholm
      - DOCKGE_STACKS_DIR=$HOME/.config/compose
    ports:
      - 5001:5001/tcp
    volumes:
      - $HOME/.config/compose:$HOME/.config/compose
      - $HOME/containers/storage/dockge/data:/app/data:rw
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
    networks:
      - proxy

networks:
  proxy:
    external: true